### ISSUE TITLE
Other neuralensemble repo GH pages sites are broken

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/neuralensemble.github.io#1]
Hi @apdavison, I see you've set this up to host the neuralensemble.org site.
It seems though this has caused other GH pages sites for repos on https://github.com/NeuralEnsemble to fail, e.g. I had a site from https://github.com/NeuralEnsemble/Networks_SIG generating to  https://neuralensemble.github.io/Networks_SIG/, but now that redirects to http://neuralensemble.org/Networks_SIG/, which gives an error.

That one is not too important, but I really would like to move neuroConstruct.org site to GH pages, and now that's saying it gets deployed at http://neuralensemble.org/neuroConstruct/, which is not the case. 

Could you look into it?

**Comment by apdavison** [comment]
Hi @pgleeson,

Sorry for breaking things for you. The process of moving neuralensemble.org is incomplete, I still need to ask Eilif to change the DNS settings, since he's the domain name owner. This is why http://neuralensemble.org/Networks_SIG/ and other GH pages sites aren't working.

For the time being, I've removed the "external domain name" option from the settings, so https://neuralensemble.github.io/Networks_SIG/ is no longer redirecting.

I'll let you know when we flip the DNS switch, so you can check everything then works.

**Comment by pgleeson** [comment]
Thanks @apdavison. I've managed to get nC hosted at https://neuralensemble.github.io/neuroConstruct, which was my main priority. I'll look into switching http://neuroconstruct.org/ over to point at this.

**Comment by apdavison** [comment]
Hi @pgleeson - Eilif and I have now set up the DNS settings for neuralensemble.org to point to Github pages.

https://neuralensemble.org/Networks_SIG and https://neuralensemble.org/neuroConstruct both now seem to work. Please check nothing is broken and let us know either way.

**Comment by pgleeson** [comment]
Great, thanks @apdavison. I need to test moving neuroConstruct.org to point at this, but it should work fine.
